### PR TITLE
Update the compiled version with recent code changes

### PR DESCRIPTION
**Pull request by jbmorley**
It looks like the 'dist' package wasn't updated as part of the recent changes. This updates index.js and licenses.txt with the result of running 'npm run package', picking up some of the changes to enable bookworm builds (see #78).

### CODE REVIEW

**Comment by jbmorley** [comment]
I had a look into this and it seems that `npm run all` isn't actually fully running. I wonder if perhaps one of the earlier phases is failing silently?

**Comment by usimd** [comment]
Hey @jbmorley! Thanks for reminding me. I did not find the time to do some cleanup and required changes (setting `bookworm` as default release and disabling qcow2 builds) that were on my mind before doing the release. 

Will do this today and release the new version.

**Comment by jbmorley** [comment]
@usimd Thanks for looking into this, and for pi-gen-action–it's incredibly helpful!

**Comment by usimd** [comment]
Much appreciated 👍
If the issue is resolved from your point of view, feel free to close the PR.

**Comment by usimd** [comment]
I added an automated workflow to create a release upon changing the version in `package.json` and subsequently compile/push the distribution package to the new tag.

Taking the liberty to close this PR. If there's anything else you need, feel free to re-open or create a new one.

**Comment by jbmorley** [comment]
Thanks!

**Pull request closed without merging**
